title:  Manisha Das
logo: /images/Myphoto1.jpg
description: I tell stories with data using SQL, Excel, and Power BI, turning information into useful insights.
#show_downloads: false
theme: jekyll-theme-minimal
